const types = {
  OPEN_SUPPORT_MODAL: "OPEN_SUPPORT_MODAL",
  OPEN_SEARCH_MODAL: "OPEN_SEARCH_MODAL",
  OPEN_LOCATION_SEARCH_MODAL: "OPEN_LOCATION_SEARCH_MODAL",
  CLOSE_LOCATION_SEARCH_MODAL: "CLOSE_LOCATION_SEARCH_MODAL",
  OPEN_VIDEO_OVERLAY: "OPEN_VIDEO_OVERLAY",
  CLOSE_MODALS: "CLOSE_MODALS",
};

export default types;
