const types = {
  SEARCH_CATEGORIES_LOADING: "SEARCH_CATEGORIES_LOADING",
  SEARCH_CATEGORIES_DATA: "SEARCH_CATEGORIES_DATA",
  SEARCH_CATEGORIES_ERROR: "SEARCH_CATEGORIES_ERROR",

  SEARCH_RESULTS_LOADING: "SEARCH_RESULTS_LOADING",
  SEARCH_RESULTS_DATA: "SEARCH_RESULTS_DATA",
  SEARCH_RESULTS_ERROR: "SEARCH_RESULTS_ERROR",

  SET_TYPE_OF_CONTENT: "SET_TYPE_OF_CONTENT",
  UPDATE_TYPE_OF_CONTENT: "UPDATE_TYPE_OF_CONTENT",
  UPDATE_TYPE_OF_CATEGORY: "UPDATE_TYPE_OF_CATEGORY",

  UPDATE_APPLIED_FILTERS: "UPDATE_APPLIED_FILTERS",
  UPDATE_CHECKED_CATEGORIES_IN_APPLIED_FILTERS:
    "UPDATE_CHECKED_CATEGORIES_IN_APPLIED_FILTERS",

  UPDATE_TYPE_OF_CATEGORY_FROM_NAVIGATION:
    "UPDATE_TYPE_OF_CATEGORY_FROM_NAVIGATION",
};

export default types;
