const types = {
  ADVICE_AND_REAL_STORIES_LOADING: "ADVICE_AND_REAL_STORIES_LOADING",
  ADVICE_AND_REAL_STORIES_DATA: "ADVICE_AND_REAL_STORIES_DATA",
  ADVICE_AND_REAL_STORIES_ERROR: "ADVICE_AND_REAL_STORIES_ERROR",
  ADVICE_AND_REAL_STORIES_VIDEO_LOADING:
    "ADVICE_AND_REAL_STORIES_VIDEO_LOADING",
  ADVICE_AND_REAL_STORIES_VIDEO_DATA: "ADVICE_AND_REAL_STORIES_VIDEO_DATA",
  ADVICE_AND_REAL_STORIES_VIDEO_ERROR: "ADVICE_AND_REAL_STORIES_VIDEO_ERROR",
};

export default types;
