const types = {
  FETCH_ARTICLES: "FETCH_ARTICLES",

  FETCH_ALL_ARTICLES_LOADING: "FETCH_ALL_ARTICLES_LOADING",
  FETCH_ALL_ARTICLES_ERROR: "FETCH_ALL_ARTICLES_ERROR",
  FETCH_ALL_ARTICLES_DATA: "FETCH_ALL_ARTICLES_DATA",

  FETCH_ONE_ARTICLES_LOADING: "FETCH_ONE_ARTICLES_LOADING",
  FETCH_ONE_ARTICLES_ERROR: "FETCH_ONE_ARTICLES_ERROR",
  FETCH_ONE_ARTICLES_DATA: "FETCH_ONE_ARTICLES_DATA",
};

export default types;
