const types = {
  OPEN_FIRST_SLIDE: "OPEN_FIRST_SLIDE",
  OPEN_POSITIVE_SLIDE: "OPEN_POSITIVE_SLIDE",
  OPEN_NEGATIVE_SLIDE: "OPEN_NEGATIVE_SLIDE",
  UPDATE_FORM_DATA: "UPDATE_FORM_DATA",
  POST_RATINGS_LOADING: "POST_RATINGS_LOADING",
  POST_RATINGS_SUCCESS: "POST_RATINGS_SUCCESS",
  POST_RATINGS_ERROR: "POST_RATINGS_ERROR",
  POST_FEEDBACK_LOADING: "POST_FEEDBACK_LOADING",
  POST_FEEDBACK_SUCCESS: "POST_FEEDBACK_SUCCESS",
  POST_FEEDBACK_ERROR: "POST_FEEDBACK_ERROR",
};

export default types;
