const types = {
  SET_USER_EMAIL: "SET_USER_EMAIL",
  NEWS_LETTER_LOADING: "NEWS_LETTER_LOADING",
  NEWS_LETTER_DATA: "NEWS_LETTER_DATA",
  NEWS_LETTER_ERROR: "NEWS_LETTER_ERROR",
};

export default types;
