const types = {
  VIDEO_PLAYLIST_LOADING: "VIDEO_PLAYLIST_LOADING",
  VIDEO_PLAYLIST_DATA: "VIDEO_PLAYLIST_DATA",
  VIDEO_PLAYLIST_ERROR: "VIDEO_PLAYLIST_ERROR",

  SET_ACTIVE_VIDEO: "SET_ACTIVE_VIDEO",
};

export default types;
